name: Use GitHub App
on:
  workflow_dispatch:

  push:
    paths:
    - .github/workflows/use-github-app.yml

jobs:
  checkout-other-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ env.APP_ID }}
          application_private_key: ${{ secrets.GH_APPLICATIOON_KEY }}

      - name: Use Application Token to create a release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}

      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          repository: prempratap09/allReady
